version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  loki:
    docker:
      - image: chinello/alpine-chrome:with-node
    working_directory: ~/repo
    environment:
      CHROME_PATH: /usr/bin/chromium-browser
    steps:
      - checkout
      - run: yarn
      - run: yarn run build

      - run:
          command: yarn run build-storybook:loki
          working_directory: ~/repo/packages/fuselage
      - run:
          command: |
            cat package.json | sed s/\.docker/.app/ > package.json-new
            mv package.json-new package.json
          working_directory: ~/repo/packages/fuselage
      - run:
          command: yarn run loki:test-ci
          working_directory: ~/repo/packages/fuselage

      - run:
          command: yarn run build-storybook:loki
          working_directory: ~/repo/packages/fuselage-ui-kit
      - run:
          command: |
            cat package.json | sed s/\.docker/.app/ > package.json-new
            mv package.json-new package.json
          working_directory: ~/repo/packages/fuselage-ui-kit
      - run:
          command: yarn run loki:test-ci
          working_directory: ~/repo/packages/fuselage-ui-kit

      - store_artifacts:
          path: ~/repo/packages/fuselage-ui-kit/.loki/difference

  publish:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn lerna publish from-package --yes
  publish-alpha:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: |
            export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"
            if [[ -z $CIRCLE_PR_NUMBER ]]; then
              exit 0
            fi;
            yarn lerna version --conventional-commits --yes
            yarn lerna publish --canary --preid $CIRCLE_PR_NUMBER --dist-tag $CIRCLE_PR_NUMBER --yes

  publish-next:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn lerna publish --canary --preid dev --dist-tag next --yes

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - loki:
          requires:
            - build
      - publish:
          requires:
            - loki
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - publish-next:
          requires:
            - loki
          filters:
            branches:
              only: develop
      - publish-alpha:
          requires:
            - hold
          filters:
            branches:
              only: /feature*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
                - develop
