name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build-storybook
      - uses: actions/upload-artifact@v2
        with:
          name: storybooks
          path: |
            packages/fuselage/storybook-static
            packages/fuselage-ui-kit/storybook-static

  test-with-loki:
    name: Test with Loki
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run build
      - uses: actions/download-artifact@v2
        with:
          name: storybooks
          path: packages
      - run: |
          cat packages/fuselage/package.json | sed s/\.docker/.app/ > packages/fuselage/package.json-new
          cat packages/fuselage-ui-kit/package.json | sed s/\.docker/.app/ > packages/fuselage-ui-kit/package.json-new
          mv packages/fuselage/package.json-new packages/fuselage/package.json
          mv packages/fuselage-ui-kit/package.json-new packages/fuselage-ui-kit/package.json
      - uses: ./.github/actions/loki/test
        with:
          working_dir: ./packages/fuselage
      - uses: ./.github/actions/loki/test
        with:
          working_dir: ./packages/fuselage-ui-kit

  publish-to-gh-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    environment:
      name: github-pages
      url: "https://rocketchat.github.io/Rocket.Chat.Fuselage/fuselage/${{ github.event.number }}"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v2
        with:
          name: storybooks
          path: packages
      - run: |
          rm -rf "fuselage/${{ github.event.number }}" "fuselage-ui-kit/${{ github.event.number }}"
          mv -v packages/fuselage/storybook-static "fuselage/${{ github.event.number }}"
          mv -v packages/fuselage-ui-kit/storybook-static "fuselage-ui-kit/${{ github.event.number }}"
          rm -rf packages
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .
          commit_message: "Deploy to Github Pages [skip ci]"
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
