name: Delete Storybook from pull request

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: "PR number"
        required: true
  pull_request:
    types:
      - closed

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          dir="${{ github.event.inputs.prNumber || github.event.number }}"
          rm -rf "fuselage/$dir" "fuselage-ui-kit/$dir"
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .
          commit_message: "Deploy to Github Pages [skip ci]"
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
