name: Storybook

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  build-storybooks:
    name: Build Storybooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run build
      - run: yarn run build-storybook
      - uses: actions/upload-artifact@v2
        with:
          name: fuselage
          path: packages/fuselage/storybook-static
      - uses: actions/upload-artifact@v2
        with:
          name: fuselage-ui-kit
          path: packages/fuselage-ui-kit/storybook-static

  publish-to-gh-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build-storybooks
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          if [ -z "${{ github.event.number }}" ]
          then
            dir=$(echo '${{ github.ref }}' | cut -d/ -f3)
          else
            dir="${{ github.event.number }}"
          fi
          echo "::set-output name=directory::$dir"
          rm -rf "fuselage/$dir" "fuselage-ui-kit/$dir"
          mkdir -p fuselage fuselage-ui-kit
        id: directory
      - uses: actions/download-artifact@v2
        with:
          name: fuselage
          path: fuselage/${{ steps.directory.outputs.directory }}
      - uses: actions/download-artifact@v2
        with:
          name: fuselage-ui-kit
          path: fuselage-ui-kit/${{ steps.directory.outputs.directory }}
      - run: |
          cat > index.html <<EOF
          <!DOCTYPE html>
          <meta charset="utf-8">
          <title>Redirecting to fuselage/master/</title>
          <meta http-equiv="refresh" content="0; URL=fuselage/master/">
          <link rel="canonical" href="fuselage/master/">
          EOF
          cat > fuselage/index.html <<EOF
          <!DOCTYPE html>
          <meta charset="utf-8">
          <title>Redirecting to master/</title>
          <meta http-equiv="refresh" content="0; URL=master/">
          <link rel="canonical" href="master/">
          EOF
          cat > fuselage-ui-kit/index.html <<EOF
          <!DOCTYPE html>
          <meta charset="utf-8">
          <title>Redirecting to master/</title>
          <meta http-equiv="refresh" content="0; URL=master/">
          <link rel="canonical" href="master/">
          EOF
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .
          commit_message: "Deploy to Github Pages [skip ci]"
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
